{
 "title": "Linux VM",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Storage Overview",
   "type": "gauge",
   "description": "Disk Space of the Linux VM",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{mountpoint=\"/\",fstype!=\"tmpfs\"} / 1024 / 1024 / 1024",
     "legendFormat": "Total (GB)"
    },
    {
     "expr": "(node_filesystem_size_bytes{mountpoint=\"/\",fstype!=\"tmpfs\"}\r\n -\r\n node_filesystem_avail_bytes{mountpoint=\"/\",fstype!=\"tmpfs\"}) \r\n/ 1024 / 1024 / 1024",
     "legendFormat": "Used (GB)"
    },
    {
     "expr": "node_filesystem_avail_bytes{mountpoint=\"/\",fstype!=\"tmpfs\"} / 1024 / 1024 / 1024",
     "legendFormat": "Available Free (GB)"
    },
    {
     "expr": "100 - ((node_filesystem_avail_bytes{mountpoint=\"/\",fstype!=\"tmpfs\"} \r\n        / node_filesystem_size_bytes{mountpoint=\"/\",fstype!=\"tmpfs\"}) * 100)",
     "legendFormat": "Usage %"
    }
   ]
  },
  {
   "title": "Memory Overview",
   "type": "gauge",
   "description": "RAM Usage of the Linux VM",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes / 1024 / 1024 / 1024",
     "legendFormat": "Total (GB)"
    },
    {
     "expr": "(node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / 1024 / 1024 / 1024",
     "legendFormat": "Used (GB)"
    },
    {
     "expr": "node_memory_MemAvailable_bytes / 1024 / 1024 / 1024",
     "legendFormat": "Available Free (GB)"
    },
    {
     "expr": "((node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes) * 100",
     "legendFormat": "Usage %"
    }
   ]
  },
  {
   "title": "CPU Usage (%)",
   "type": "timeseries",
   "description": "CPU Usage of the Linux VM",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "CPU Usage %"
    }
   ]
  },
  {
   "title": "Uptime (Hours)",
   "type": "stat",
   "description": "Uptime of the Linux VM",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(node_time_seconds - node_boot_time_seconds) / 3600",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk IOPS",
   "type": "timeseries",
   "description": "Reads and Writes happening in the Linux VM",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "rate(node_disk_reads_completed_total{device=\"sda\"}[5m])",
     "legendFormat": "Reads ({{device}})"
    },
    {
     "expr": "rate(node_disk_writes_completed_total{device=\"sda\"}[5m])",
     "legendFormat": "Writes ({{device}})"
    }
   ]
  },
  {
   "title": "Updates Available",
   "type": "gauge",
   "description": "Total Number of Updates available ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "updates_available_total", "legendFormat": "Firmware Updates Available" }
   ]
  },
  {
   "title": "Network Traffic (Inbound & Outbound)",
   "type": "timeseries",
   "description": "Inbound & Outbound traffic in the Linux VM",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{device=\"enp0s3\"}[5m])",
     "legendFormat": "Inbound Traffic"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{device=\"enp0s3\"}[5m])",
     "legendFormat": "Outbound Traffic"
    }
   ]
  }
 ]
}